theme: jekyll-theme-slate
title: [PIVO&colon; Probabilistic inertial-visual odometry for occlusion-robust navigation]
description: [<a href="http://arno.solin.fi">Arno Solin</a>, Santiago Cortes, Esa Rahtu, and Juho Kannala]
