theme: jekyll-theme-slate
title: [PIVO&colon; Probabilistic inertial-visual odometry for occlusion-robust navigation]
description: [[Arno Solin](http://arno.solin.fi), Santiago Cortes, Esa Rahtu, and Juho Kannala]
