theme: jekyll-theme-slate
title: "PIVO: Probabilistic inertial-visual odometry for occlusion-robust navigation"
description: "Published in WACV 2018</ br><a class='site-link' href='http://arno.solin.fi'>Arno Solin</a>"
